targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: none
          include_if_null: true
          explicit_to_json: true
          create_factory: true
          create_to_json: true
