// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx0jdhDDiKx9Mr0aRhin_xyJnFu7Iczz8',
    appId: '1:512503175866:android:6bd2de3ac1ccc5580cc083',
    messagingSenderId: '512503175866',
    projectId: 'convo-chat-e1918',
    storageBucket: 'convo-chat-e1918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHDs6Somk2WOuz63FgVAgjqpuhe0xW-jo',
    appId: '1:512503175866:ios:e3d0f6a0a90961b60cc083',
    messagingSenderId: '512503175866',
    projectId: 'convo-chat-e1918',
    storageBucket: 'convo-chat-e1918.firebasestorage.app',
    androidClientId: '512503175866-ju5gj5biqbsuj5nnnoj5kllpvubkbo35.apps.googleusercontent.com',
    iosClientId: '512503175866-siqqmaaac8hqnmfb0tgcjotbak8n3ofc.apps.googleusercontent.com',
    iosBundleId: 'app.convo.chat',
  );

}